### ISSUE TITLE
TypeError: Plain typing.TypeAlias is not valid as type argument

### ISSUE THREAD

**Issue by hydrochloricacid** [CosmosShadow/gptpdf#1]
parse page: 0
parse page: 1
parse page: 2
parse page: 3
parse page: 4
parse page: 5
parse page: 6
parse page: 7
parse page: 8
parse page: 9
parse page: 10
parse page: 11
parse page: 12
parse page: 13
parse page: 14
Traceback (most recent call last):
  File "D:\gptpdf-main\gptpdf-main\main.py", line 4, in <module>
    content, image_paths = parse_pdf(pdf_path, api_key=api_key)
  File "D:\gptpdf-main\gptpdf-main\gptpdf\parse.py", line 284, in parse_pdf
    content = _gpt_parse_images(image_infos, output_dir=output_dir, api_key=api_key, base_url=base_url, model=model, verbose=verbose)
  File "D:\gptpdf-main\gptpdf-main\gptpdf\parse.py", line 225, in _gpt_parse_images
    from GeneralAgent import Agent
  File "D:\anaconda\envs\LLM\lib\site-packages\GeneralAgent\__init__.py", line 2, in <module>
    from .agent.agent import Agent
  File "D:\anaconda\envs\LLM\lib\site-packages\GeneralAgent\agent\agent.py", line 6, in <module>
    from GeneralAgent.interpreter import Interpreter
  File "D:\anaconda\envs\LLM\lib\site-packages\GeneralAgent\interpreter\__init__.py", line 4, in <module>
    from .knowlege_interpreter import KnowledgeInterperter
  File "D:\anaconda\envs\LLM\lib\site-packages\GeneralAgent\interpreter\knowlege_interpreter.py", line 3, in <module>
    from GeneralAgent.llamaindex import create_llamaindex, load_llamaindex, query_llamaindex
  File "D:\anaconda\envs\LLM\lib\site-packages\GeneralAgent\llamaindex.py", line 6, in <module>
    from llama_index.core import Settings
  File "D:\anaconda\envs\LLM\lib\site-packages\llama_index\core\__init__.py", line 19, in <module>
    from llama_index.core.indices import (
  File "D:\anaconda\envs\LLM\lib\site-packages\llama_index\core\indices\__init__.py", line 32, in <module>
    from llama_index.core.indices.loading import (
  File "D:\anaconda\envs\LLM\lib\site-packages\llama_index\core\indices\loading.py", line 6, in <module>
    from llama_index.core.indices.registry import INDEX_STRUCT_TYPE_TO_INDEX_CLASS
  File "D:\anaconda\envs\LLM\lib\site-packages\llama_index\core\indices\registry.py", line 13, in <module>
    from llama_index.core.indices.property_graph import PropertyGraphIndex
  File "D:\anaconda\envs\LLM\lib\site-packages\llama_index\core\indices\property_graph\__init__.py", line 1, in <module>
    from llama_index.core.indices.property_graph.base import PropertyGraphIndex
  File "D:\anaconda\envs\LLM\lib\site-packages\llama_index\core\indices\property_graph\base.py", line 17, in <module>
    from llama_index.core.indices.property_graph.transformations import (
  File "D:\anaconda\envs\LLM\lib\site-packages\llama_index\core\indices\property_graph\transformations\__init__.py", line 4, in <module>
    from llama_index.core.indices.property_graph.transformations.schema_llm import (
  File "D:\anaconda\envs\LLM\lib\site-packages\llama_index\core\indices\property_graph\transformations\schema_llm.py", line 116, in <module>
    class SchemaLLMPathExtractor(TransformComponent):
  File "D:\anaconda\envs\LLM\lib\site-packages\llama_index\core\indices\property_graph\transformations\schema_llm.py", line 153, in SchemaLLMPathExtractor
    possible_entities: Optional[TypeAlias] = None,
  File "D:\anaconda\envs\LLM\lib\typing.py", line 309, in inner
    return func(*args, **kwds)
  File "D:\anaconda\envs\LLM\lib\typing.py", line 400, in __getitem__
    return self._getitem(self, parameters)
  File "D:\anaconda\envs\LLM\lib\typing.py", line 525, in Optional
    arg = _type_check(parameters, f"{self} requires a single type.")
  File "D:\anaconda\envs\LLM\lib\typing.py", line 169, in _type_check
    raise TypeError(f"Plain {arg} is not valid as type argument")
TypeError: Plain typing.TypeAlias is not valid as type argument
请问如何解决？

**Comment by CosmosShadow** [comment]
This issue is caused by llama-index. You Can update your Python version to >3.10.0 to fix this.

**Comment by CosmosShadow** [comment]
close
