### ISSUE TITLE
 Error: No module named 'gptpdf'

### ISSUE THREAD

**Issue by ageekor** [CosmosShadow/gptpdf#13]
Traceback (most recent call last):
  File "D:\Python\gptpdf\test\test.py", line 47, in <module>
    test_use_api_key()
  File "D:\Python\gptpdf\test\test.py", line 8, in test_use_api_key
    from gptpdf import parse_pdf
ModuleNotFoundError: No module named 'gptpdf'

how to solve this? thank you

**Comment by CosmosShadow** [comment]
please 'pip install gptpdf' before.
