### ISSUE TITLE
GLM 支持出现问题

### ISSUE THREAD

**Issue by Jalen-Zhong** [CosmosShadow/gptpdf#39]
问题：
使用glm-4v时报错。本地与服务器两个环境皆出现该问题。

错误日志如下：
```
2024-07-25 15:03:07,659 - ERROR - LLM(Large Languate Model) error, Please check your key or base_url, or network
Traceback (most recent call last):
  File "/root/anaconda3/envs/vllm_pdf/lib/python3.9/site-packages/GeneralAgent/skills/llm_inference.py", line 167, in _llm_inference_with_stream
    response = client.chat.completions.create(
  File "/root/anaconda3/envs/vllm_pdf/lib/python3.9/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/vllm_pdf/lib/python3.9/site-packages/openai/resources/chat/completions.py", line 646, in create
    return self._post(
  File "/root/anaconda3/envs/vllm_pdf/lib/python3.9/site-packages/openai/_base_client.py", line 1266, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/root/anaconda3/envs/vllm_pdf/lib/python3.9/site-packages/openai/_base_client.py", line 942, in request
    return self._request(
  File "/root/anaconda3/envs/vllm_pdf/lib/python3.9/site-packages/openai/_base_client.py", line 1046, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'timestamp': '2024-07-25T07:03:07.620+00:00', 'status': 404, 'error': 'Not Found', 'path': '/v4/chat/completions/chat/completions'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/vllm_pdf/lib/python3.9/site-packages/GeneralAgent/agent/agent.py", line 325, in _llm_and_parse_output
    for token in response:
  File "/root/anaconda3/envs/vllm_pdf/lib/python3.9/site-packages/GeneralAgent/skills/llm_inference.py", line 184, in _llm_inference_with_stream
    raise ValueError('LLM(Large Languate Model) error, Please check your key or base_url, or network')
ValueError: LLM(Large Languate Model) error, Please check your key or base_url, or network
LLM(Large Languate Model) error, Please check your key or base_url, or network
```

版本：
gptpdf == 0.0.15
GeneralAgent == 0.3.23

诉求：

虽然issue#15 有同样的问题，目前按issue步骤操作仍然无法解决该问题。烦请开发者测试一下。

**Comment by zRzRzRzRzRzRzR** [comment]
GLM应该有报错链接吧，GLM的配置 要把 v4 也放进去

**Comment by CosmosShadow** [comment]
看 'path': '/v4/chat/completions/chat/completions' 这个报错，应该是你的base_url填写错误。
