### ISSUE TITLE
支持deepseek

### ISSUE THREAD

**Issue by inspirewind** [CosmosShadow/gptpdf#41]
使用deepseek api时报错
`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/inspirewind/miniconda3/envs/graphrag/lib/python3.12/site-packages/GeneralAgent/agent/agent.py", line 325, in _llm_and_parse_output
    for token in response:
  File "/Users/inspirewind/miniconda3/envs/graphrag/lib/python3.12/site-packages/GeneralAgent/skills/llm_inference.py", line 184, in _llm_inference_with_stream
    raise ValueError('LLM(Large Languate Model) error, Please check your key or base_url, or network')
ValueError: LLM(Large Languate Model) error, Please check your key or base_url, or network
2024-07-29 11:33:37,490 - INFO - gpt parse page: 11
2024-07-29 11:33:38,621 - INFO - HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 422 Unprocessable Entity"
2024-07-29 11:33:38,622 - ERROR - Failed to deserialize the JSON body into the target type: messages[1]: invalid type: sequence, expected a string at line 1 column 486954
Traceback (most recent call last):
  File "/Users/inspirewind/miniconda3/envs/graphrag/lib/python3.12/site-packages/GeneralAgent/skills/llm_inference.py", line 167, in _llm_inference_with_stream
    response = client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/inspirewind/miniconda3/envs/graphrag/lib/python3.12/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/inspirewind/miniconda3/envs/graphrag/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 646, in create
    return self._post(
           ^^^^^^^^^^^
  File "/Users/inspirewind/miniconda3/envs/graphrag/lib/python3.12/site-packages/openai/_base_client.py", line 1266, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/inspirewind/miniconda3/envs/graphrag/lib/python3.12/site-packages/openai/_base_client.py", line 942, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/inspirewind/miniconda3/envs/graphrag/lib/python3.12/site-packages/openai/_base_client.py", line 1046, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: invalid type: sequence, expected a string at line 1 column 486954
2024-07-29 11:33:38,624 - ERROR - LLM(Large Languate Model) error, Please check your key or base_url, or network
Traceback (most recent call last):
  File "/Users/inspirewind/miniconda3/envs/graphrag/lib/python3.12/site-packages/GeneralAgent/skills/llm_inference.py", line 167, in _llm_inference_with_stream
    response = client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/inspirewind/miniconda3/envs/graphrag/lib/python3.12/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/inspirewind/miniconda3/envs/graphrag/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 646, in create
    return self._post(
           ^^^^^^^^^^^
  File "/Users/inspirewind/miniconda3/envs/graphrag/lib/python3.12/site-packages/openai/_base_client.py", line 1266, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/inspirewind/miniconda3/envs/graphrag/lib/python3.12/site-packages/openai/_base_client.py", line 942, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/inspirewind/miniconda3/envs/graphrag/lib/python3.12/site-packages/openai/_base_client.py", line 1046, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[1]: invalid type: sequence, expected a string at line 1 column 486954

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/inspirewind/miniconda3/envs/graphrag/lib/python3.12/site-packages/GeneralAgent/agent/agent.py", line 325, in _llm_and_parse_output
    for token in response:
  File "/Users/inspirewind/miniconda3/envs/graphrag/lib/python3.12/site-packages/GeneralAgent/skills/llm_inference.py", line 184, in _llm_inference_with_stream
    raise ValueError('LLM(Large Languate Model) error, Please check your key or base_url, or network')
ValueError: LLM(Large Languate Model) error, Please check your key or base_url, or network
LLM(Large Languate Model) error, Please check your key or base_url, or network

LLM(Large Languate Model) error, Please check your key or base_url, or network

LLM(Large Languate Model) error, Please check your key or base_url, or network

LLM(Large Languate Model) error, Please check your key or base_url, or network

LLM(Large Languate Model) error, Please check your key or base_url, or network

LLM(Large Languate Model) error, Please check your key or base_url, or network

LLM(Large Languate Model) error, Please check your key or base_url, or network

LLM(Large Languate Model) error, Please check your key or base_url, or network

LLM(Large Languate Model) error, Please check your key or base_url, or network

LLM(Large Languate Model) error, Please check your key or base_url, or network

LLM(Large Languate Model) error, Please check your key or base_url, or network

LLM(Large Languate Model) error, Please check your key or base_url, or network`

**Comment by zRzRzRzRzRzRzR** [comment]
额 ds API没有视觉模型啊

**Comment by CosmosShadow** [comment]
> 额 ds API没有视觉模型啊

yes.
